---
- name: Clean FTP footage
  hosts: nas
  gather_facts: false

  tasks:
  - name: Run ftp cam footage cleanup
    # uploades the specified script and executes it as directed. Seems path needs to be relative since the working directory is the directory the playbook is in
    ansible.builtin.script: ../../../scripts/nas/cleanup_ftp_cam_footage.sh 2>&1 | tee -a /share/MD0_DATA/ftp/cleanup.log
    register: cleanup_output

  # use minimal instead for cleaner output: https://serverfault.com/a/842944
  - debug: var=cleanup_output.stdout_lines