---
- name: Copy progress
  hosts: qnap-nas
  gather_facts: false

  tasks:
  - name: Calculating progress...
    # uploads the specified script and executes it as directed. Seems path needs to be relative since the working directory is the directory the playbook is in
    ansible.builtin.script: ../../../scripts/qnap-nas/copy_files_monitoring.sh | tee -a /share/MD0_DATA/copy.log
    register: result
    # until: result.stdout.find("all systems go") != -1
    # retries: 99999999999
    # delay: 10
    # failed_when: false  # Prevents task from failing outright, enabling retries
    # ignore_errors: true  #

  # - name: Progress...
  #   debug:
  #     msg: "Output: {{ result.stdout }}"
  #   when: result.stdout is defined

  # use minimal instead for cleaner output: https://serverfault.com/a/842944
  - debug: var=result.stdout_lines