---
- name: Update Proxmox and Ceph repositories
  hosts: proxmox
  become: yes
  tasks:
    - name: Comment out Proxmox enterprise repository in pve-enterprise.list
      replace:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        regexp: '^deb .*proxmox.com.* .* enterprise'
        replace: '# \g<0>'

    - name: Add Proxmox no-subscription repository in pve-enterprise.list
      lineinfile:
        path: /etc/apt/sources.list.d/pve-enterprise.list
        line: 'deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription'

    - name: Comment out Ceph Quincy repository in ceph.list
      replace:
        path: /etc/apt/sources.list.d/ceph.list
        regexp: '^deb .*proxmox.com/.*ceph-quincy .* enterprise'
        replace: '# \g<0>'

    - name: Add Ceph Quincy no-subscription repository in ceph.list
      lineinfile:
        path: /etc/apt/sources.list.d/ceph.list
        line: 'deb http://download.proxmox.com/debian/ceph-quincy bookworm no-subscription'