# Baed on suggestions from chat GPU based on a Lenovo M75Q with Ryzen 5650GE and 32 GB of RAM
# Custom stuff added like nag removal
---
# Via: https://github.com/ironicbadger/ansible-role-proxmox-nag-removal/blob/master/tasks/remove-nag.yml
# Consider switching to this...
# echo "DPkg::Post-Invoke { \"dpkg -V proxmox-widget-toolkit | grep -q '/proxmoxlib\.js$'; if [ \$? -eq 1 ]; then { echo 'Removing subscription nag from UI...'; sed -i '/.*data\.status.*{/{s/\!//;s/active/NoMoreNagging/}' /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js; }; fi\"; };" >/etc/apt/apt.conf.d/no-nag-script
# via https://www.reddit.com/r/selfhosted/comments/1gxsgb5/comment/lyl2epo/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button
# Also note the rollback step...
# apt reinstall proxmox-widget-toolkit
- name: Remove nag message
  replace:
    path: /usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js
    regexp: 'res[\s\n]*\.data\.status\.toLowerCase\(\) !== .active.'
    replace: "false"
    backup: yes

- name: restart pveproxy
  service:
    name: pveproxy
    state: restarted

- name: Add Proxmox non-subscription repository
  copy:
    dest: /etc/apt/sources.list.d/pve-no-subscription.list
    content: |
      deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription

- name: Rename enterprise repository file to keep a backup
  command:
    cmd: mv /etc/apt/sources.list.d/pve-enterprise.list /etc/apt/sources.list.d/pve-enterprise.list.bak
  args:
    removes: /etc/apt/sources.list.d/pve-enterprise.list
  changed_when: true

- name: Update apt cache after adding repository
  apt:
    update_cache: yes

- name: Update and upgrade the system
  apt:
    upgrade: dist

- name: Enable IOMMU in GRUB
  lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT'
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet amd_iommu=on iommu=pt"'

- name: Update GRUB configuration
  command: update-grub
  when: ansible_facts.os_family == "Debian"

- name: Set swappiness to 10
  sysctl:
    name: vm.swappiness
    value: 10
    state: present

- name: Discover active network interfaces
  shell: "ip -o link show | awk -F': ' '/state UP/ {print $2}'"
  register: active_interfaces

- name: Enable Jumbo Frames on active interfaces
  loop: "{{ active_interfaces.stdout_lines }}"
  command: ip link set mtu 9000 dev {{ item }}
  ignore_errors: yes

# - name: Install essential packages
#   apt:
#     name:
#       - qemu-guest-agent
#       - pciutils
#     state: present

# # - name: Install Fail2ban
# #   apt:
# #     name: fail2ban
# #     state: present

# # - name: Configure Fail2ban for Proxmox Web GUI
# #   blockinfile:
# #     path: /etc/fail2ban/jail.local
# #     block: |
# #       [proxmox]
# #       enabled = true
# #       port = 8006
# #       filter = proxmox
# #       logpath = /var/log/pveproxy/access.log
# #       maxretry = 3

# # - name: Restart Fail2ban
# #   service:
# #     name: fail2ban
# #     state: restarte