---
- name: Clean FTP footage
  hosts: vector
  gather_facts: false

  tasks:
    - name: Find files older than x days
      find:
        paths: /media/ext_storage/ftp/cam-ftp/
        # This will wipe the top level camera directories since they were originally created at the very start of when the content started to be written into the ftp directory.
        # The timestamps of the folders at that level don't get updated when newer files / folder get written within them. Ouch
        # file_type: directory
        age: 14d
        recurse: yes
      register: oldFiles
    - name: Remove older than x days
      become: true
      file:
        path: "{{ item.path }}" 
        state: absent
      with_items: "{{ oldFiles.files }}"