---
- name: Docker system prune
  hosts: "{{ hosts }}"
  gather_facts: false

  tasks:
  - name: Run docker system prune
    ansible.builtin.raw: sudo docker system prune -f
    register: output

  - debug: var=output.stdout_lines