# source: https://www.cyberciti.biz/faq/ansible-apt-update-all-packages-on-ubuntu-debian-linux/

# PREREQUISITES
# - /etc/sudoers/<username> file contains lines below. Replace user 'maintenance' with whatever the username is you are using for SSH
# maintenance ALL=(ALL:ALL) NOPASSWD: /usr/bin/sh # For Ansible to use become for running privileged commands

---
- hosts: "{{ TARGET_HOSTS }}"
  become: true
  gather_facts: no
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    # Seems to hang Semaphore sometimes. Could be if Docker or other specific packages get updated and interrupt the Semaphore run?
    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes

    - name: Check if a reboot is needed on all servers
      register: reboot_required_file
      stat: path=/var/run/reboot-required # get_md5=no

    # - name: Reboot the box if kernel updated
    #   reboot:
    #     msg: "Reboot initiated by Ansible for kernel updates"
    #     connect_timeout: 5
    #     reboot_timeout: 300
    #     pre_reboot_delay: 0
    #     post_reboot_delay: 30
    #     test_command: uptime
    #   when: reboot_required_file.stat.exists

    - name: Reboot
      shell: sleep 2 && shutdown -r now "Ansible reboot after host upgrade"
      async: 1
      poll: 0
      ignore_errors: true
      when: reboot_required_file.stat.exists