---
- hosts: all
  become: true
  gather_facts: no
  vars:
    # script_name: nas_share_monitoring
    script_dir: "/root/scripts"
    scripts:
      # Disable since moving to new NAS since it keeps the array spun up and the NAS awake
      # - nas_share_monitoring.sh
      - external_drive_monitoring.sh

  tasks:
    - name: Ensure destination directory exists
      file:
        path: "{{ script_dir }}"
        state: directory

    - name: Copy monitoring script to destination
      copy:
        src: "../../../scripts/hosts/monitoring/{{ item }}"
        dest: "{{ script_dir }}"
        mode: '+x'
      loop: "{{ scripts }}"


    - name: Configure cron job for monitoring script
      ansible.builtin.cron:
        name: "Run script {{ item }}"
        minute: "*/5"
        job: "{{ script_dir }}/{{ item }} > {{ script_dir }}/{{ item }}.log"
      loop: "{{ scripts }}"