---
- hosts: all
  become: true
  vars:
    nas_share_monitor_script_name: nas_share_monitoring.sh
    nas_share_monitor_script_path: "/root/scripts/{{ nas_share_monitor_script_name }}"

  tasks:
    # Currently needs to be run as the root user because of how the network share is mapped by the root user
    # I think because some of the docker containers are running as root? I can't remember.
    - name: Copy monitoring scripts to run locations
      ansible.builtin.copy:
        src: "../../../scripts/hosts/monitoring/{{ nas_share_monitor_script_name }}"
        dest: "{{ nas_share_monitor_script_path }}"
        mode: '+x'

    - name: Configure cron job for monitoring
      ansible.builtin.cron:
        name: "nas share monitor"
        minute: "*/5"
        job: "{{ nas_share_monitor_script_path }} > /dev/null"