---
- name: Configure CIFS mount for ReplicateOut
  hosts: localhost
  become: yes
  
  vars:
    MOUNT_POINT: /mnt/nas_replicate_out
    # was using mcp but ansible playbooks that leverage this share use the maintenance user and it's less permissive than the mcp user
    MOUNT_USER: maintenance

  vars_prompt:
    - name: NAS_USERNAME
      prompt: "Enter username for {{ MOUNT_POINT }} share. Default:"
      private: yes
      default: networkbackup
    - name: NAS_PASSWORD
      prompt: "Enter password for {{ MOUNT_POINT }} share"
      private: yes

  tasks:
    - name: Install cifs-utils
      apt:
        name: cifs-utils
        state: present
        update_cache: yes

    - name: Create SMB credentials file
      copy:
        dest: /root/.smbcredentials_replicate_out_master_control
        content: |
          username={{ NAS_USERNAME }}
          password={{ NAS_PASSWORD }}
        owner: root
        group: root
        mode: '0600'

    - name: Ensure the mount point directory exists
      file:
        path: "{{ MOUNT_POINT }}"
        state: directory
        owner: "{{ MOUNT_USER }}"
        group: "{{ MOUNT_USER }}"
        mode: '0750'

    - name: Add CIFS entry to /etc/fstab
      lineinfile:
        path: /etc/fstab
        line: "//storage.ournetwork.ca/ReplicateOut {{ MOUNT_POINT }} cifs uid={{ MOUNT_USER }},credentials=/root/.smbcredentials_replicate_out_master_control 0 0"
        state: present

    - name: Mount the CIFS share
      command: mount -a
      register: MOUNT_RESULT
      changed_when: MOUNT_RESULT.rc == 0

    - name: Display result of mount
      debug:
        msg: "Mount result: {{ MOUNT_RESULT }}"