---
- name: Create Samba Users
  hosts: all
  gather_facts: no
  become: yes
  vars:
    media_user: "media"
  vars_prompt:
    - name: "media_samba_password"
      prompt: "Enter the Samba password for the media user"
      private: yes

  tasks:
    - name: Debug before user creation
      debug:
        msg: "About to create the media user"

    - name: Create media user
      become: true
      user:
        name: "{{ media_user }}"
        state: present
        shell: "/usr/sbin/nologin"
        password_lock: yes
        create_home: no

    - name: Debug after user creation
      debug:
        msg: "Media user created successfully"

    - name: Set Samba password for the media user
      command: "echo -ne '{{ media_samba_password }}\n{{ media_samba_password }}\n' | smbpasswd -s -a {{ media_user }}"
      args:
        creates: "/var/lib/samba/private/passdb.tdb"