---
- name: Setup media directories and Samba
  hosts: all
  gather_facts: no
  become: yes

  vars:
    samba_workgroup: "FILESERVERS"
    media_user: "media"
    media_folders:
      audio:
        path: "/media/ext_storage/audio"
        browsable: yes
        writable: yes
        read_only: no
      photos:
        path: "/media/ext_storage/photos"
        browsable: yes
        writable: yes
        read_only: no
      videos:
        path: "/media/ext_storage/videos"
        browsable: yes
        writable: yes
        read_only: no

  tasks:
    - name: Install samba package
      apt:
        name: samba
        state: present
        update_cache: yes

    - name: Ensure media directories exist
      file:
        path: "{{ item.value.path }}"
        state: directory
        owner: "{{ media_user }}"
        group: "{{ media_user }}"
        mode: '0755'
      loop: "{{ media_folders | dict2items }}"
      loop_control:
        label: "{{ item.key }}"

    - name: Backup the original Samba configuration with timestamp
      copy:
        src: /etc/samba/smb.conf
        dest: "/etc/samba/smb.conf.bak_{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}"
        remote_src: yes
        backup: yes

    - name: Update Samba workgroup
      lineinfile:
        path: /etc/samba/smb.conf
        regexp: '^workgroup ='
        line: "workgroup = {{ samba_workgroup }}"
        backup: yes

    - name: Add Samba shares to the smb.conf
      blockinfile:
        path: /etc/samba/smb.conf
        insertafter: EOF
        block: |
          [audio]
          path = {{ media_folders.audio.path }}
          valid users = @{{ media_user }}
          browsable = yes
          writable = yes
          read only = no

          [photos]
          path = {{ media_folders.photos.path }}
          valid users = @{{ media_user }}
          browsable = yes
          writable = yes
          read only = no

          [videos]
          path = {{ media_folders.videos.path }}
          valid users = @{{ media_user }}
          browsable = yes
          writable = yes
          read only = no

    - name: Restart Samba services
      service:
        name: smbd
        state: restarted
      notify: restart smbd

  handlers:
    - name: restart smbd
      service:
        name: smbd
        state: restarted
